runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      with:
        fetch-depth: '1'
        path: ./phpstan-adjust-scandirs
        repository: Icinga/github-actions
        ref: php-workflow

    - name: Install Dependencies
      working-directory: ./phpstan-adjust-scandirs/.github/actions/phpstan-adjust-scandirs
      shell: bash
      run: composer install --no-progress --prefer-dist # --no-dev

    - name: Adjust PHPStan scanDirectories
      shell: bash
      run: ./phpstan-adjust-scandirs/.github/actions/phpstan-adjust-scandirs/bin/phpstan-adjust-scandirs phpstan.neon "$PHPSTAN_SCANDIRS"
