inputs:
  php-version:
    type: string
    required: true
    description: 'PHP versions to test against, JSON encoded array of strings.'
  php-extensions:
    type: string
    description: 'PHP extensions to install, comma separated list of strings.'
  php-tools:
    type: string
  dependencies:
    type: string
    description: 'Dependencies to install, JSON encoded map of path => repository url.'
    default: '{}'
  working-directory:
    required: false
    type: string
    default: .

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      with:
        fetch-depth: '1'

    - name: Setup PHP
      uses: shivammathur/setup-php@bf6b4fbd49ca58e4608c9c89fba0b8d90bd2a39f # v2.35.5
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ${{ inputs.php-extensions }}
        tools: ${{ inputs.php-tools }}

    - name: composer install
      if: hashFiles('composer.json') != ''
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: composer install --no-progress --prefer-dist # --no-dev

    - name: Setup module and dependencies
      if: hashFiles('module.info') != ''
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        git clone --depth 1 https://github.com/Icinga/icingaweb2.git vendor/icingaweb2
        echo "PHPUNIT_BOOTSTRAP=$(readlink -f vendor/icingaweb2/test/php/bootstrap.php)" >> $GITHUB_ENV

        git clone --depth 1 -b snapshot/nightly https://github.com/Icinga/icinga-php-library.git vendor/icinga-php/ipl
        git clone --depth 1 -b snapshot/nightly https://github.com/Icinga/icinga-php-thirdparty.git vendor/icinga-php/vendor
        echo "ICINGAWEB_LIBDIR=$(readlink -f vendor/icinga-php)" >> $GITHUB_ENV

        echo "PHPSTAN_SCANDIRS=$(readlink -f vendor)" >> $GITHUB_ENV

        mkdir -p tests/modules
        ln -s "$(pwd)" tests/modules/$(awk '/^Module:/ {print $2}' module.info)
        echo "ICINGAWEB_MODULES_DIR=$(readlink -f vendor/icingaweb2/modules):$(readlink -f tests/modules)" >> $GITHUB_ENV

    - name: Setup additional dependencies
      if: ${{ inputs.dependencies != '{}' }}
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        echo "$json" | jq -r 'to_entries[] | "\(.key)\u0000\(.value)"' | while IFS=$'\0' read -r path url; do
          echo "Cloning $url into $path..."
          git clone -q --depth 1 "$url" "./$path"
        done
